### ISSUE TITLE
Unable to load texture

### ISSUE THREAD

**Issue by toktoktheeo** [BlueDuckYT/More-Jellyfish#2]
Hi,

I got this when a slime jellyfish tried to spawn:

`[14:57:39] [Render thread/WARN] [minecraft/TextureManager]: Failed to load texture: more_jellyfish:textures/entity/slime_jellyfish
java.io.FileNotFoundException: more_jellyfish:textures/entity/slime_jellyfish
	at net.minecraft.resources.FallbackResourceManager.func_199002_a(FallbackResourceManager.java:63) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:61) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.renderer.texture.SimpleTexture$TextureData.func_217799_a(SourceFile:81) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.texture.SimpleTexture.func_215246_b(SourceFile:57) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.texture.SimpleTexture.func_195413_a(SourceFile:28) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.texture.TextureManager.func_230183_b_(TextureManager.java:94) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.texture.TextureManager.func_229263_a_(TextureManager.java:65) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.texture.TextureManager.func_229269_d_(TextureManager.java:58) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:49) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.RenderState$TextureState.func_228605_a_(SourceFile:206) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.RenderState.func_228547_a_(SourceFile:32) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorRenderState,pl:mixin:A}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[guava-21.0.jar:?] {}
	at net.minecraft.client.renderer.RenderType$Type.func_228674_b_(SourceFile:838) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.RenderState.func_228547_a_(SourceFile:32) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorRenderState,pl:mixin:A}
	at net.minecraft.client.renderer.RenderType.func_228631_a_(SourceFile:599) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.IRenderTypeBuffer$Impl.func_228462_a_(SourceFile:86) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.client.renderer.IRenderTypeBuffer$Impl.getBuffer(SourceFile:45) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:118) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(SourceFile:43) ~[?:?] {re:classloading}
	at blueduck.morejellyfish.morejellyfishmod.client.renderer.SlimeJellyfishRenderer.render(SlimeJellyfishRenderer.java:33) ~[more_jellyfish:1.0] {re:classloading}
	at blueduck.morejellyfish.morejellyfishmod.client.renderer.SlimeJellyfishRenderer.func_225623_a_(SlimeJellyfishRenderer.java:18) ~[more_jellyfish:1.0] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1197) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1005) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.4-client.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.28-launcher.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}`

Have a nice day.

**Comment by BlueDuckYT** [comment]
What version are you on? Also, did it crash or just spam the log?

**Comment by toktoktheeo** [comment]
Hi,

Very sorry, I'm on Minecraft 1.16.4 with forge 35.1.28 and More Jellyfish 1.1.1.

It does not crash but I got this regularly.
